/** @brief Set of macros mapping CONTROLLINO aliases to Arduino pin numbers
 *
 *  For CONTROLLINO MAXI Automation
 */

#ifdef CONTROLLINO_MAXI_AUTOMATION

  #define CONTROLLINO_ETHERNET_CHIP_SELECT 70
  #define CONTROLLINO_ETHERNET_INTERRUPT 71
  #define CONTROLLINO_RTC_CHIP_SELECT 72
  #define CONTROLLINO_RTC_INTERRUPT 73
  #define CONTROLLINO_OVERLOAD 74

  #define CONTROLLINO_PIN_HEADER_PWM_00 2
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_00 2
  #define CONTROLLINO_SCREW_TERMINAL_PWM_00 2
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_OUT_00 2
  
  #define CONTROLLINO_PIN_HEADER_PWM_01 3
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_01 3
  #define CONTROLLINO_SCREW_TERMINAL_PWM_01 3
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_OUT_01 3
  
  #define CONTROLLINO_PIN_HEADER_PWM_02 4
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_02 4
  #define CONTROLLINO_SCREW_TERMINAL_PWM_02 4
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_OUT_02 4
  
  #define CONTROLLINO_PIN_HEADER_PWM_03 5
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_03 5
  #define CONTROLLINO_SCREW_TERMINAL_PWM_03 5
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_OUT_03 5
  
  #define CONTROLLINO_PIN_HEADER_PWM_04 6
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_04 6
  #define CONTROLLINO_SCREW_TERMINAL_PWM_04 6
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_OUT_04 6
  
  #define CONTROLLINO_PIN_HEADER_PWM_05 7
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_05 7
  #define CONTROLLINO_SCREW_TERMINAL_PWM_05 7
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_OUT_05 7
  
  #define CONTROLLINO_PIN_HEADER_PWM_06 8
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_06 8
  #define CONTROLLINO_SCREW_TERMINAL_PWM_06 8
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_OUT_06 8
  
  #define CONTROLLINO_PIN_HEADER_PWM_07 9
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_07 9
  #define CONTROLLINO_SCREW_TERMINAL_PWM_07 9
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_OUT_07 9
  
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_00 66
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_00 66
  
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_01 67
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_01 67
  
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_02 10
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_02 10
  
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_03 11
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_03 11
  
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_OUT_00 12
  
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_OUT_01 13
  
  #define CONTROLLINO_UART_TX 16
  
  #define CONTROLLINO_UART_RX 17
  
  #define CONTROLLINO_PIN_HEADER_INT_00 18
  #define CONTROLLINO_SCREW_TERMINAL_INT_00 18
  
  #define CONTROLLINO_PIN_HEADER_INT_01 19
  #define CONTROLLINO_SCREW_TERMINAL_INT_01 19
  
  #define CONTROLLINO_PIN_HEADER_SDA 20
  
  #define CONTROLLINO_PIN_HEADER_SCL 21
  
  #define CONTROLLINO_RELAY_00 22
  
  #define CONTROLLINO_RELAY_01 23
  
  #define CONTROLLINO_RELAY_02 24
  
  #define CONTROLLINO_RELAY_03 25
  
  #define CONTROLLINO_RELAY_04 26
  
  #define CONTROLLINO_RELAY_05 27
  
  #define CONTROLLINO_RELAY_06 28
  
  #define CONTROLLINO_RELAY_07 29
  
  #define CONTROLLINO_RELAY_08 30
  
  #define CONTROLLINO_RELAY_09 31
  
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_12 42
  
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_13 43
  
  #define CONTROLLINO_PIN_HEADER_PWM_12 44
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_14 44
  
  #define CONTROLLINO_PIN_HEADER_PWM_13 45
  #define CONTROLLINO_PIN_HEADER_DIGITAL_OUT_15 45
  
  #define CONTROLLINO_PIN_HEADER_MISO 50
  
  #define CONTROLLINO_PIN_HEADER_MOSI 51
  
  #define CONTROLLINO_PIN_HEADER_SCK 52
  
  #define CONTROLLINO_PIN_HEADER_SS 53
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_00 54
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_00 54
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_00 54 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_00 54
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_01 55
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_01 55
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_01 55 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_01 55
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_02 56
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_02 56
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_02 56 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_02 56
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_03 57
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_03 57
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_03 57 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_03 57
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_04 58
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_04 58
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_04 58 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_04 58
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_04 58
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_04 58
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_05 59
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_05 59
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_05 59 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_05 59
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_05 59
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_05 59
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_06 60
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_06 60
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_06 60 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_06 60
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_06 60
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_06 60
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_07 61
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_07 61
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_07 61 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_07 61
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_07 61
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_07 61
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_08 62
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_08 62
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_08 62 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_08 62
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_08 62
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_08 62
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_09 63
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_09 63
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_ADC_IN_09 63 
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_09 63
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_09 63
  #define CONTROLLINO_SCREW_TERMINAL_DIGITAL_IN_09 63
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_10 64
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_10 64
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_10 64
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_10 64
  
  #define CONTROLLINO_PIN_HEADER_ANALOG_ADC_IN_11 65
  #define CONTROLLINO_PIN_HEADER_DIGITAL_ADC_IN_11 65
  #define CONTROLLINO_PIN_HEADER_DIGITAL_IN_11 65
  #define CONTROLLINO_SCREW_TERMINAL_ANALOG_ADC_IN_11 65
  
  #define CONTROLLINO_DO0 2
  #define CONTROLLINO_DO1 3
  #define CONTROLLINO_DO2 4
  #define CONTROLLINO_DO3 5
  #define CONTROLLINO_DO4 6
  #define CONTROLLINO_DO5 7
  #define CONTROLLINO_DO6 8
  #define CONTROLLINO_DO7 9
  
  /* just for compatibility with the common examples */
  #define CONTROLLINO_D0 2
  #define CONTROLLINO_D1 3
  #define CONTROLLINO_D2 4
  #define CONTROLLINO_D3 5
  #define CONTROLLINO_D4 6
  #define CONTROLLINO_D5 7
  #define CONTROLLINO_D6 8
  #define CONTROLLINO_D7 9
  
  #define CONTROLLINO_A0 54
  #define CONTROLLINO_A1 55
  #define CONTROLLINO_A2 56
  #define CONTROLLINO_A3 57
  #define CONTROLLINO_A4 58
  #define CONTROLLINO_A5 59
  #define CONTROLLINO_A6 60
  #define CONTROLLINO_A7 61
  #define CONTROLLINO_A8 62
  #define CONTROLLINO_A9 63
  #define CONTROLLINO_A10 64
  #define CONTROLLINO_A11 65
  
  #define CONTROLLINO_A12 68
  #define CONTROLLINO_A13 69
  /* END - just for compatibility with the common examples - END */
  
  #define CONTROLLINO_DI0 66
  #define CONTROLLINO_DI1 67
  #define CONTROLLINO_DI2 10
  #define CONTROLLINO_DI3 11
  
  #define CONTROLLINO_AO0 12
  #define CONTROLLINO_AO1 13
  
  #define CONTROLLINO_AI0 54
  #define CONTROLLINO_AI1 55
  #define CONTROLLINO_AI2 56
  #define CONTROLLINO_AI3 57
  #define CONTROLLINO_AI4 58
  #define CONTROLLINO_AI5 59
  #define CONTROLLINO_AI6 60
  #define CONTROLLINO_AI7 61
  #define CONTROLLINO_AI8 62
  #define CONTROLLINO_AI9 63
  #define CONTROLLINO_AI10 64
  #define CONTROLLINO_AI11 65
  
  #define CONTROLLINO_AI12 68
  #define CONTROLLINO_AI13 69
  
  #define CONTROLLINO_IN0 18
  #define CONTROLLINO_IN1 19
  
  #define CONTROLLINO_R0 22
  #define CONTROLLINO_R1 23
  #define CONTROLLINO_R2 24
  #define CONTROLLINO_R3 25
  #define CONTROLLINO_R4 26
  #define CONTROLLINO_R5 27
  #define CONTROLLINO_R6 28
  #define CONTROLLINO_R7 29
  #define CONTROLLINO_R8 30
  #define CONTROLLINO_R9 31
  
#endif

